[package]
name = "loutre_hublot"
version = "0.2.0"
authors = ["Edgar Onghena <dev@edgar.bzh>"]
edition = "2018"

[dependencies]
dotenv = "0.15.0"
lettre = { version = "0.10.2", features = ["file-transport", "tokio1-native-tls"] }
log = "0.4.17"
rocket = "0.5.0-rc.2"
